### ISSUE TITLE
Integrate Sentry for logging

### ISSUE THREAD

**Issue by drewcook** [arbor-protocol/ui#198]
# Chore

Please provide details for the chore needing to be done.  This should likely be technical debt or other updates that won't affect the existing functionality of the app.

**What needs to be done?**

We have an account with Sentry and integrated with our Heroku CI/CD.  We have an existing branch and draft PR open here #109.  This work should continue off of the previous work already done and in the same branch.

Sentry Dashboard: https://sentry.io/arbor-protocol/arbor-ui/

We should be logging all of our http requests to sentry, including errors, warnings, successes, etc.  Here are a few resources to get started:

- Next.js package: https://github.com/vercel/next.js/tree/canary/examples/with-sentry
- Sentry docs: https://sentry.io/integrations/heroku/ & https://docs.sentry.io/product/integrations/deployment/heroku/
- Heroku docs: https://elements.heroku.com/addons/sentry

**Comment by drewcook** [comment]
To whomever picks this up - please reach out to me directly with your email address so I can add you in as a member to our Sentry dashboard.

**Comment by noahdahlman** [comment]
@drewcook can we get an update on the status of sentry ?
