### ISSUE TITLE
Show recent activity on latest 3 projects.

### ISSUE THREAD

**Issue by noahdahlman** [arbor-protocol/ui#223]
# Feature

Please fill in these details describing the enhancement or improvement you'd like to see to the existing functionality within the UI.  Please be as specific as possible.

**What would you like to see improved or updated?**

Show the most recently updated 3 project below banner on the homepage.

Card with a centered title "Recent Activity" , with a 3 column layout of `ProjectCard` components. These project cards should be from the most recent `updatedAt` fields in mongo.

**Comment by drewcook** [comment]
Create this as it's own component, maybe something like `<RecentProjectActivity />` so it contains all the logic for loading the projects and sorting/filtering/mapping and rendering. THen import that into the `<Home />` component
