### ISSUE TITLE
Separate routes for RecentProjectActivity 

### ISSUE THREAD

**Issue by noahdahlman** [arbor-protocol/ui#233]
I have a few things as feedback on how this initially got implemented. I'd like the get them addressed in this PR as a follow-up.

The initial PR got merged in without my feedback at all, and the way the projects are getting are wrong - it should limit the results to 3. I think it needs to be moved to it's own route, and or the params passed in need to be ensured that they are working on the records correctly, or if they need to be translated to direct `mongoose` helper methods and moved to its own route, like `/projects/recent`, which always returns the latest three.

_Originally posted by @drewcook in https://github.com/arbor-protocol/ui/issues/229#issuecomment-1356834294_

**Comment by 0xlws** [comment]
first commit 
moved request to its own route, results limited to 3: [commit](https://github.com/arbor-protocol/ui/pull/237/commits/76b9c75e6d27f00a530ad839e66a06bd1e1faac6).
let me know about the implementation
