### ISSUE TITLE
Replace nested Card components with a top level <section> in RecentProjectActivity.

### ISSUE THREAD

**Issue by noahdahlman** [arbor-protocol/ui#234]
Another feedback item is how `<Card>` is used in this. It's applied as a top-level global component, then maps over
 the projects and renders the appropriate `ProjectCard`, which is also a card.  So this isn't ideal. The top level card 
component, card header, card contents, IMO should be split up to a `<section>`, for the overall topmost component for 
`RecentProjectActivity`, as it's used on the homepage, and the title can just be a typography h3 or whatever and the 
subtext  another typography centered. Then the cards don't have to be wrapped in anything after that.  So this will 
remove `Card, CardContent, CardHeader` from the component.

_Originally posted by @drewcook in https://github.com/arbor-protocol/ui/issues/229#issuecomment-1356834710_

**Comment by drewcook** [comment]
See `<Box>` example in #235
